<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>BigFix ActionScript</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#relevance_substitution</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\s*//.*</string>
			<key>name</key>
			<string>comment.line.double-slash.bigfix.actionscript</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"|$</string>
			<key>name</key>
			<string>string.quoted.double.bigfix.actionscript</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#relevance_substitution</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\\"</string>
					<key>name</key>
					<string>constant.character.escape.bigfix.actionscript</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>^\s*(if|continue if|elseif|else|endif)</string>
			<key>name</key>
			<string>keyword.control.bigfix.actionscript</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^\s*(createfile until)\s*(.*)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.command.bigfix.actionscript</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.createfile.bigfix.actionscript</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>string.unquoted.createfile.bigfix.actionscript</string>
			<key>end</key>
			<string>\2</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.createfile.bigfix.actionscript</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>match</key>
			<string>^\s*(action (launch preference (low|normal)-priority|lock (indefinite|until)|may require restart|parameter query|requires (login|restart)|unlock|uses wow64 redirection)|add (nohash )?prefetch item|administrative rights (enable|disable)|administrator (add|delete)|appendfile|archive now|begin prefetch block|browse to|collect prefetch items|copy|custom site (un)?subscribe|delete|dos|download( now as| as)?|enable gathering|end prefetch block|execute prefetch plug-in|exit|extract|fixlet (close|delete|restore)|folder (create|delete)|module (add|commit|delete)|move|notify client|open|override (run|wait)|parameter|pause while|prefetch|regdelete(64)?|regset(64)?|relay select|restart|script(64)?|set clock|setting( delete)?|shutdown|site (force evaluation|gather schedule (disable|manual|publisher|seconds))|(un)?subscribe|utility|(run|wait)(detached|hidden)?)</string>
			<key>name</key>
			<string>keyword.command.bigfix.actionscript</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>relevance_substitution</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>{</string>
					<key>end</key>
					<string>}</string>
					<key>name</key>
					<string>constant.character.escape.bigfix.actionscript</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>}}</string>
							<key>name</key>
							<string>meta.brace.curly.bigfix.actionscript</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>text.bigfix.actionscript</string>
	<key>uuid</key>
	<string>84D3C83E-890E-4527-AFAA-E5DD72B59566</string>
</dict>
</plist>
